import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "./components/Header/Header";
import { BiSearchAlt2 } from "react-icons/bi";
import Footer from "./components/footer/footer";
import { Footerlogo, links, logoValue, menus } from "./mockdata";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header logo={logoValue} links={links} ActionIcon={BiSearchAlt2} />
        <section className="mx-[65px]">{children}</section>
        <Footer menus={menus} logo={Footerlogo} />
      </body>
    </html>
  );
}
